
version: "3"

services:
  prerender:
    container_name: fluentd
    image: fluent/fluentd:edge-debian
    volumes:
      - ./etc/fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
    expose:
      - 24224